name: auto_fix
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  graphql: ^5.0.0
  graphql_flutter: ^5.0.0
  webview_flutter: ^2.0.13
  shared_preferences: ^2.0.7
  http: ^0.13.3
  cached_network_image: ^3.1.0+1
  google_maps_flutter: ^2.1.3
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  path_provider: ^2.0.4
  image_picker: 0.8.4+1
  flutter_staggered_grid_view: ^0.4.1
  month_picker_dialog: ^0.4.0
  another_xlider: ^1.0.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  connectivity_plus: ^1.2.0
  carousel_slider: 4.0.0
  # FACEBOOK PACKAGE
  flutter_facebook_login: 2.0.1
  # FIREBASE PACKAGES
  google_sign_in: 5.1.0
  firebase_core: 1.11.0
  firebase_auth: 2.0.0
  firebase_storage: ^10.2.8
  firebase_messaging: 10.0.4
  dio: ^4.0.4

  animations: ^2.0.0
  country_code_picker: ^2.0.2
  sms_otp_auto_verify: ^2.1.0
  flutter_xlider: ^3.4.0
  flutter_svg: 0.23.0+1
  intl: ^0.17.0
  geolocator: ^8.2.0
  geocoding: ^2.0.2
  file_picker: ^4.5.0
  fdottedline: ^1.0.1
  slider_button: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/image/
    - assets/image/login/
    - assets/image/forgotPwd/
    - assets/image/UserType/
    - assets/image/CustomerType/
    - assets/image/MechanicType/
    - assets/image/phoneLogin/
    - assets/image/SignUp/
    - assets/image/mechanicProfileView/
    - assets/image/mechanicProfileView/curvedGray.png
    - assets/fonts/
    - assets/json/
    - assets/image/home_customer/
    - assets/image/home_customer/banner1.png
    - assets/image/mechanicProfileView/directionMechnanicTracking.svg
    - assets/map_style/map_style.json
    - assets/image/mechanicTracking/
    - assets/image/MechanicType/incomingRequestBg.svg
    - assets/image/IconsRatingBar/
    - assets/image/CustomerType/mechanicArrivedBg.svg

  fonts:
    - family: Montserrat_SemiBold
      fonts:
        - asset: assets/fonts/Montserrat_SemiBold.ttf
    - family: Montserrat_Light
      fonts:
        - asset: assets/fonts/Montserrat_Light.ttf
    - family: Corbel_Light
      fonts:
        - asset: assets/fonts/corbell.ttf
    - family: Corbel_Bold
      fonts:
        - asset: assets/fonts/corbel_bold.ttf
    - family: Corbel_Regular
      fonts:
        - asset: assets/fonts/corbel.ttf
    - family: Samsung_SharpSans_Bold
      fonts:
          - asset: assets/fonts/samsungsharpsans-bold.otf
    - family: Samsung_SharpSans_Regular
      fonts:
          - asset: assets/fonts/samsungsharpsans.otf
    - family: Samsung_SharpSans_Medium
      fonts:
          - asset: assets/fonts/samsungsharpsans-medium.otf
    - family: harpSans_Medium
      fonts:
          - asset: assets/fonts/Sharp Sans Medium.otf
    - family: SharpSans_Semibold
      fonts:
          - asset: assets/fonts/Sharp Sans Semibold.otf
    - family: SharpSans_Bold
      fonts:
          - asset: assets/fonts/SharpSansBold.otf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
